name: Publish Report to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "allure-results/**"
      - "kanvas-results/**"
      - "meshery-results/**"
      - "meshery-server-results/**"
      - "mesheryctl-results/**"
      - "mesheryctl-bats-results/**"
      - "mesheryctl-unit-results/**"
      - "remote-provider-results/**"
      - "allurerc.mjs"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Allure Report 🔧
        run: make report-build

      - name: Commit & push updated history
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update allure history"
          commit_options: "--signoff"
          file_pattern: history.jsonl
          commit_user_name: meshery-ci
          commit_user_email: ci@meshery.io

      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: "./allure-report"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    needs: build
    steps:
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v5.0.0

